#!/bin/bash

# Remove decomposition subdirs
rm -rf processor*

# Remove log files
rm -r output xdmf_b h5Data

# Clear any reconstructed results
#foamCleanTutorials

# And delete mesh
foamClearPolyMesh

